# Generated by Django 5.2.6 on 2025-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
            ],
        ),
    ]
