# Generated by Django 5.2.8 on 2025-12-16 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='contact_clicks',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='programmer',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], default='Junior', max_length=20),
        ),
        migrations.AddField(
            model_name='programmer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmer',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='programmer',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_projects', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_projects', to='marketplace.programmer')),
            ],
        ),
    ]
