# Generated by Django 5.2.8 on 2025-12-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_programmer_contact_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='programmer',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
