# Generated by Django 5.2.6 on 2025-11-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_user_bio_user_category_user_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(default='Web Developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programmers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
