# Generated by Django 5.2.8 on 2025-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_programmer_bank_name_programmer_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
