# Generated by Django 5.2.6 on 2025-12-09 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_programmer_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='contact_clicks',
        ),
        migrations.AlterField(
            model_name='programmer',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='portfolio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='skills',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
