# Generated by Django 5.2.6 on 2025-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_programmer_contact_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='review_count',
        ),
        migrations.AddField(
            model_name='programmer',
            name='contact_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
