# Generated by Django 5.2.6 on 2025-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_programmer_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
