# Generated by Django 5.2.6 on 2026-01-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_programmer_bank_name_remove_programmer_iban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='contact_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProfileContactClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_tracking', to='marketplace.programmer')),
            ],
            options={
                'unique_together': {('client', 'programmer')},
            },
        ),
    ]
